### ISSUE TITLE
Setup and Initialize Project

### ISSUE THREAD

**Issue by pixelbuildlab** [pixelbuildlab/auth-kit#1]
## TODO: Setup and Initialize Project

- [x] 1 **Initialize Git Repository:**
   - Run `git init` in the project root.

- [x] 2. **Configure Git User:**
   - Set local username and email with:
     ```bash
     git config user.name "pixelbuildlab"
     git config user.email "2017n2801@gmail.com"
     ```

- [x] 3. **Create `.gitignore` File:**
   - Add common files and directories to `.gitignore`:
     ```
     node_modules/
     .env
     *.log
     ```

- [x] 4. **Make Initial Commit:**
   - Stage and commit initial project files:
     ```bash
     git add .
     git commit -m "Initial commit"
     ```

- [x] 5. **Set Up Remote Repository (Optional):**
   - Add remote repository URL if applicable:
     ```bash
     git remote add origin https://github.com/pixelbuildlab/auth-kit.git
     ```

- [x] 6. **Push Initial Commit (Optional):**
   - Push changes to the remote repository:
     ```bash
     git push -u origin main
     ```

- [x] 7. **Verify Setup:**
   - Ensure that the local Git configuration and `.gitignore` are correctly applied.

---
